### PR TITLE
Auto-add http:// to links - fixes #346

### LINKED ISSUE #346: Link without http:// in mere info does not work
Just realised from an event that if the user writes www.tidtilfred.nu the page directs to https//dukop.dk/events/www.tidtilfred.nu - which of course does not exist. It works if I add http://
Would be good to change the behaviour, if possible, so that the links work when people only write www.something.ex

### PR DESCRIPTION
**Pull request by benjaoming**
Passes tests locally

Fixes #346

### CODE REVIEW

**Comment by ronan-mch** [comment]
Should it be a `before_save` hook rather than `before_validation`?

**Comment by benjaoming** [comment]
I think it should be before validation! :)

**Comment by ronan-mch** [comment]
Why? Is it because you also want there to be a validation connected to the
issue? Note that it is possible to skip validation from save, so if that
was done the before_validation hook wouldn't be run. Also, regarding tests,
could you please add a test for the case when there is a http:// in front
of the image?

**Comment by benjaoming** [comment]
> Note that it is possible to skip validation from save, so if that was done the before_validation hook wouldn't be run.

Sounds a bit speculative :) I think it's fine to clean up the data before passing it on the the validation part. If somehow that's skipped, then that's probably with good reason (like loading in data from fixtures or whatever)

**Comment by benjaoming** [comment]
> Also, regarding tests, could you please add a test for the case when there is a http:// in front of the image?

Not sure I understand? Image?

**Comment by ronan-mch** [comment]
sorry, I meant link. Just so that you're testing both cases.

**Comment by benjaoming** [comment]
@ronan-mch ^

**Comment by ronan-mch** [comment]
yep, go for it.

**Pull request merged**
