### PR TITLE
Add RSS feed at /feed.rss

### PR DESCRIPTION
**Pull request by localresource**
Add RSS feed at /feed.rss.

### CODE REVIEW

**Comment by benjaoming** [comment]
Looks fine, should we try to just deploy it and see how it looks?

**Comment by localresource** [comment]
That would be great. Can you do that @benjaoming?

**Comment by benjaoming** [comment]
Is this the correct URL? Does the result look as expected?

https://www.dukop.dk/?format=rss

**Comment by localresource** [comment]
The URL is https://www.dukop.dk/feed.rss

It looks 'good enough'. Maybe I need to change the order of the events. They should probably be listed by creation date instead.

I will talk to the Konfront people and tweak it so it fits their needs in a few days.

**Comment by benjaoming** [comment]
Open as many PRs as you want, will happily deploy 'em all :)

**Pull request merged**
